### PR TITLE
Allow to use a callback function as a response

### PR DESCRIPTION
**Pull request by piranna**
This allow to do some actions when a particular input is found

### CODE REVIEW

**Comment by jprichardson** [comment]
Thank you. Would you be able to add a test?

**Comment by piranna** [comment]
Test done ;-)

**Comment by piranna** [comment]
Any update on this?

**Comment by jprichardson** [comment]
I'll review it next week :)

On Friday, January 30, 2015, Jesús Leganés Combarro <
notifications@github.com> wrote:

> Any update on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jprichardson/node-suppose/pull/8#issuecomment-72264525>
> .
>


-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow me on Twitter: http://twitter.com/jprichardson

**Comment by piranna** [comment]
Ok ;-)

**Comment by jprichardson** [comment]
Eeeks, super sorry on this!!

**Comment by jprichardson** [comment]
I'm really sorry I took so long on this I missed it. I just ran the tests and they fail. Presumably because it's testing using `npm` and npm's output has changed. If you're still interested in the project I will gladly add you to it and add you to npm.

**Comment by piranna** [comment]
Hi JP. Yes, I'm still interested on the project since I'm using it for some basic sanity-checks on NodeOS, and it would be awesome if you could give me access to the project (and npm itself? omg! :-P). Why are you using npm? You could be able to use an ad-hoc script, isn't it?

**Comment by jprichardson** [comment]
LOL, I already added you! Not sure when I did...

**Comment by jprichardson** [comment]
Ah, found an old email conversation on Feb 6th. I added you then :) You've had both push/write access to Github/npm since then :)

**Comment by piranna** [comment]
Lol! It's true :-P

**Comment by piranna** [comment]
Shouldn't be published a new version on npm?

**Comment by jprichardson** [comment]
Sure, go for it :)

**Pull request merged**
